const productFolderDictionary = {
    'capacity-planner-docs': 'docs/capacity-planner/latest',
    'faq-docs': 'docs/faq',
    'geneos-aws-cloudwatch-docs': 'docs/geneos/collection/aws-cloudwatch/current',
    'geneos-fluentd-docs': 'docs/geneos/collection/fluentd/current',
    'geneos-google-cloud-platform-docs': 'docs/geneos/collection/google-cloud-platform/current',
    'geneos-jdbc-docs': 'docs/geneos/collection/jdbc/current',
    'geneos-kubernetes-docs': 'docs/geneos/collection/kubernetes/current',
    'geneos-marketsio-docs': 'docs/geneos/collection/marketsio/current',
    'geneos-mongodb-docs': 'docs/geneos/collection/mongodb/current',
    'geneos-opentelemetry-docs': 'docs/geneos/collection/opentelemetry/current',
    'geneos-prometheus-docs': 'docs/geneos/collection/prometheus/current',
    'geneos-remote-rtds-docs': 'docs/geneos/collection/remote-rtds/current',
    'geneos-statsd-docs': 'docs/geneos/collection/statsd/current',
    'geneos-vmware-docs': 'docs/geneos/collection/vmware/current',
    'geneos-docs': 'docs/geneos/current',
    'geneos-azure-monitor-docs': 'docs/geneos/collection/azure-monitor/current',
    'global-docs': 'docs/all',
    'gateway-hub-docs': '/geneos-gateway-hub/current',
    'infrastructure-agent-docs': 'docs/infrastructure-agent/current',
    'obcerv-app-alerting-docs': 'docs/itrs-analytics/app/alerting/current',
    'obcerv-app-api-gateway-docs': 'docs/itrs-analytics/app/api-gateway/current',
    'obcerv-app-centralised-config-docs': 'docs/itrs-analytics/app/centralised-config/current',
    'obcerv-app-commands-docs': 'docs/itrs-analytics/app/commands/current',
    'obcerv-app-cp-docs': 'docs/itrs-analytics/app/capacity-planner/current',
    'obcerv-app-dashboards-docs': 'docs/itrs-analytics/app/dashboards/current',
    'obcerv-app-entities-docs': 'docs/itrs-analytics/app/entities/current',
    'obcerv-app-fixmonitor-docs': 'docs/itrs-analytics/app/fixmonitor/current',
    'obcerv-app-ingestion-docs': 'docs/itrs-analytics/app/ingestion/current',
    'obcerv-app-notifications-docs': 'docs/itrs-analytics/app/notifications/current',
    'obcerv-app-query-service-docs': 'docs/itrs-analytics/app/query-service/current',
    'obcerv-app-signal-forecaster-docs': 'docs/itrs-analytics/app/signal-forecaster/current',
    'obcerv-app-systemoverview-docs': 'docs/itrs-analytics/app/overview/current',
    'obcerv-app-traces-docs': 'docs/itrs-analytics/app/traces/current',
    'obcerv-app-webconsole-docs': 'docs/itrs-analytics/app/webconsole/current',
    'obcerv-grafana-datasource-docs': 'docs/itrs-analytics/app/grafana-datasource/current',
    'obcerv-meta-docs': 'docs/itrs-analytics/current',
    'obcerv-platform-docs': 'docs/itrs-analytics/platform/current',
    'itrs-analytics-app-alerting-docs' : 'docs/itrs-analytics/app/alerting/current',
    'itrs-analytics-app-api-gateway-docs': 'docs/itrs-analytics/app/api-gateway/current',
    'itrs-analytics-app-centralised-config-docs': 'docs/itrs-analytics/app/centralised-config/current',
    'itrs-analytics-app-commands-docs': 'docs/itrs-analytics/app/commands/current',
    'itrs-analytics-app-cp-docs': 'docs/itrs-analytics/app/capacity-planner/current',
    'itrs-analytics-app-dashboards-docs': 'docs/itrs-analytics/app/dashboards/current',
    'itrs-analytics-app-entities-docs': 'docs/itrs-analytics/app/entities/current',
    'itrs-analytics-app-fixmonitor-docs': 'docs/itrs-analytics/app/fixmonitor/current',
    'itrs-analytics-app-ingestion-docs': 'docs/itrs-analytics/app/ingestion/current',
    'itrs-analytics-app-notifications-docs': 'docs/itrs-analytics/app/notifications/current',
    'itrs-analytics-app-query-service-docs': 'docs/itrs-analytics/app/query-service/current',
    'itrs-analytics-app-signal-forecaster-docs': 'docs/itrs-analytics/app/signal-forecaster/current',
    'itrs-analytics-app-systemoverview-docs': 'docs/itrs-analytics/app/overview/current',
    'itrs-analytics-app-traces-docs': 'docs/itrs-analytics/app/traces/current',
    'itrs-analytics-app-webconsole-docs': 'docs/itrs-analytics/app/webconsole/current',
    'itrs-analytics-grafana-datasource-docs': 'docs/itrs-analytics/app/grafana-datasource/current',
    'itrs-analytics-meta-docs': 'docs/itrs-analytics/current',
    'itrs-analytics-platform-docs': 'docs/itrs-analytics/platform/current',    
    'opsview-docs': 'docs/opsview/current'
};


module.exports = productFolderDictionary;